# Generated by Django 4.1.4 on 2022-12-29 00:58

import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default='', max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, default='', max_length=250)),
                ('question_type', models.CharField(blank=True, choices=[('Written-response', 'Written Response'), ('Multiple-choice', 'Multiple Choice'), ('True-or-false', 'True or False')], default='', max_length=20)),
                ('choices', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, default='', max_length=150), blank=True, default=list, size=4)),
                ('feedback', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.feedback')),
            ],
        ),
        migrations.CreateModel(
            name='FeedbackResponse',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('response', models.JSONField(blank=True, default=dict)),
                ('is_submitted', models.BooleanField(default=False)),
                ('feedback', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.feedback')),
            ],
        ),
    ]
