DEFAULT_NUM_QUESTIONS = 0
MAX_NUM_QUESTIONS = 5

DEFAULT_MULTIPLE_CHOICE_OPTIONS = 4
DEFAULT_WRITTEN_ANSWER_MAX_LENGTH = 256
DEFAULT_WRITTEN_ANSWER_MIN_LENGTH = 20
QUESTION_TITLE_MAX_LENGTH = 100
QUESTION_BODY_MAX_LENGTH = 250