# Generated by Django 4.1.4 on 2022-12-29 01:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='tier',
            field=models.CharField(choices=[(0, 'Free'), (1, 'Mid'), (2, 'Pro')], default=0, max_length=2),
        ),
    ]
